"""Structural state-store contract shared by JSON and SQLite stores."""

from __future__ import annotations

from typing import Any, Protocol

from ..domain.protocol import Event, Step, Task, ToolResult


class StateStore(Protocol):
    def save_task(self, task: Task) -> None: ...
    def save_step(self, step: Step) -> None: ...
    def save_tool_result(self, result: ToolResult) -> None: ...
    def append_event(self, event: Event) -> None: ...
    def checkpoint(self, *, task_id: str, step_id: str, phase: str, state: dict[str, Any]) -> None: ...
    def load_latest_checkpoint(self, task_id: str) -> dict[str, Any] | None: ...
    def load_task(self, task_id: str) -> Task | None: ...
    def get_idempotent(self, key: str) -> ToolResult | None: ...
    def save_idempotent(self, key: str, result: ToolResult) -> None: ...
    def get_effect_intent(self, key: str) -> dict[str, Any] | None: ...
    def create_effect_intent(self, key: str, *, task_id: str, tool_name: str, arguments: dict[str, Any]) -> bool: ...
    def complete_effect_intent(self, key: str, result: ToolResult) -> None: ...
    def mark_effect_unknown(self, key: str, *, reason: str) -> None: ...
    def transition_effect_intent(self, key: str, *, to_status: str, result: dict[str, Any] | None = None, lease_proof: Any | None = None) -> None: ...
    def record_provider_audit(self, *, task_id: str, request_id: str, intent_key: str | None, provider_id: str, resource_id: str, native_unit: str, estimated_cost_minor: int | None, price_currency: str | None, outcome: str, details: dict[str, Any] | None = None) -> None: ...
    def list_provider_audits(self, *, task_id: str | None = None, request_id: str | None = None) -> list[dict[str, Any]]: ...
    def commit_transition(self, *, task: Task | None = None, step: Step | None = None, checkpoint: dict[str, Any] | None = None, event: Event | None = None, events: list[Event] | None = None, tool_result: ToolResult | None = None, lease_proof: Any | None = None) -> None: ...
    def reconcile_effect_intent(self, key: str, *, status: str, actor: str, source: str, external_id: str | None = None, evidence: dict[str, Any] | None = None, result: ToolResult | None = None) -> None: ...
    def save_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, actor: str, call_id: str, arguments_hash: str, expires_at: float | None = None) -> None: ...
    def has_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, call_id: str, arguments_hash: str) -> bool: ...
    def consume_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, call_id: str, arguments_hash: str) -> bool: ...
    def revoke_approval(self, approval_id: str) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
    def has_event(self, task_id: str, event_type: str) -> bool: ...
