"""Structural state-store contract shared by JSON and SQLite stores."""

from __future__ import annotations

from typing import Any, Protocol

from ..domain.protocol import Event, Step, Task, ToolResult


class StateStore(Protocol):
    def save_task(self, task: Task) -> None: ...
    def save_step(self, step: Step) -> None: ...
    def save_tool_result(self, result: ToolResult) -> None: ...
    def append_event(self, event: Event) -> None: ...
    def checkpoint(self, *, task_id: str, step_id: str, phase: str, state: dict[str, Any]) -> None: ...
    def load_latest_checkpoint(self, task_id: str) -> dict[str, Any] | None: ...
    def load_task(self, task_id: str) -> Task | None: ...
    def get_idempotent(self, key: str) -> ToolResult | None: ...
    def save_idempotent(self, key: str, result: ToolResult) -> None: ...
    def get_effect_intent(self, key: str) -> dict[str, Any] | None: ...
    def create_effect_intent(self, key: str, *, task_id: str, tool_name: str, arguments: dict[str, Any]) -> bool: ...
    def complete_effect_intent(self, key: str, result: ToolResult) -> None: ...
    def save_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, actor: str, call_id: str, arguments_hash: str) -> None: ...
    def has_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, call_id: str, arguments_hash: str) -> bool: ...
    def consume_approval(self, approval_id: str, *, task_id: str, side_effect_level: str, call_id: str, arguments_hash: str) -> bool: ...
    def snapshot(self) -> dict[str, Any]: ...
