"""Narrow structural views over the shared SQLite state facade."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..domain.protocol import Event, Task


@runtime_checkable
class TaskStateView(Protocol):
    def save_task(self, task: Task) -> None: ...
    def load_task(self, task_id: str) -> Task | None: ...
    def commit_transition(self, *, task: Task | None = None, event: Event | None = None, lease_proof: Any | None = None) -> None: ...
    def snapshot(self) -> dict[str, Any]: ...
    def has_event(self, task_id: str, event_type: str) -> bool: ...


@runtime_checkable
class EventStore(Protocol):
    def append_event(self, event: Event) -> None: ...
    def append_event_if_absent(self, event: Event) -> bool: ...


@runtime_checkable
class EffectIntentStore(Protocol):
    def get_effect_intent(self, key: str) -> dict[str, Any] | None: ...
    def create_effect_intent(self, key: str, *, task_id: str, tool_name: str, arguments: dict[str, Any]) -> bool: ...
    def claim_effect_intent(self, key: str, *, expected_statuses: set[str] | frozenset[str] | tuple[str, ...], result: dict[str, Any] | None = None) -> bool: ...
    def transition_effect_intent(self, key: str, *, to_status: str, result: dict[str, Any] | None = None, lease_proof: Any | None = None) -> None: ...
    def reconcile_effect_intent(self, key: str, *, status: str, actor: str, source: str, external_id: str | None = None, evidence: dict[str, Any] | None = None, result: Any | None = None) -> None: ...


@runtime_checkable
class ProviderAuditStore(Protocol):
    def record_provider_audit(self, *, task_id: str, request_id: str, intent_key: str | None, provider_id: str, resource_id: str, native_unit: str, estimated_cost_minor: int | None, price_currency: str | None, outcome: str, details: dict[str, Any] | None = None) -> None: ...
    def list_provider_audits(self, *, task_id: str | None = None, request_id: str | None = None) -> list[dict[str, Any]]: ...


__all__ = ["EffectIntentStore", "EventStore", "ProviderAuditStore", "TaskStateView"]
